name: portfolio_kiran
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0
  url_launcher: ^6.1.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
